### PR TITLE
updated and adjusted ja.yml #1

### PR DESCRIPTION
**Pull request by sanak**

### CODE REVIEW

**Comment by dkastl** [comment]
@sanak , are you sure, that keys in YAML start with semicolon?
```
:key: value
````
shouldn't be this?
```
key: value
```

**Comment by dkastl** [comment]
Also I think the `lang` directory is something, that is not following plugin conventions. Maybe it's old style, but I don't think we need to maintain any translation outside `config/locales` directory:
https://github.com/bizyman/redmine_mail_reminder/tree/develop/config/locales

**Comment by sanak** [comment]
@dkastl 
> are you sure, that keys in YAML start with semicolon?

Yes, starting with semicolon seems to be standard of the plugin.
https://github.com/bizyman/redmine_mail_reminder/blob/develop/config/locales/en.yml

> Also I think the `lang` directory is something, that is not following plugin conventions. Maybe it's old style, but I don't think we need to maintain any translation outside `config/locales` 
 directory:

Yes, I dropped `lang` folder's `ja.yml` modification at 2nd commit.

**Comment by dkastl** [comment]
Well, the problem is, that I don't know any other plugin starting with a semicolon:
https://github.com/bizyman/redmine_scheduling_poll/blob/master/config/locales/en.yml
https://github.com/bizyman/redmine_send_issue_reply_email/blob/master/config/locales/en.yml
https://github.com/bizyman/redmine_my_page/blob/master/config/locales/en.yml
https://github.com/bizyman/redmine_impersonate/blob/master/config/locales/en.yml
https://github.com/bizyman/sidebar_hide/blob/master/config/locales/en.yml

I hope, this semicolon is just ignored and not required.

**Comment by dkastl** [comment]
Maybe Ruby specific: https://stackoverflow.com/questions/31673857/colon-in-the-front-yaml-syntax

**Pull request merged**
